# Generated by Django 6.0 on 2026-03-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('action_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('collection_view', 'Collection View'), ('cart_update', 'Cart Update'), ('search', 'Search')], default='page_view', max_length=50)),
                ('page_url', models.URLField(max_length=2048)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.URLField(blank=True, default='', max_length=2048)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Action',
                'verbose_name_plural': 'Client Actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('shop_domain', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_action', models.ForeignKey(blank=True, help_text='The action that triggered this proactive message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_messages', to='chat.clientaction')),
            ],
            options={
                'verbose_name': 'Proactive Message',
                'verbose_name_plural': 'Proactive Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
