# Generated by Django 6.0 on 2026-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(help_text="The merchant's Shopify domain, e.g. 'store.myshopify.com'", max_length=255, unique=True)),
                ('access_token', models.CharField(help_text='OAuth access token for API calls', max_length=255)),
                ('scope', models.TextField(blank=True, default='', help_text='Comma-separated list of granted OAuth scopes')),
                ('nonce', models.CharField(blank=True, default='', help_text='CSRF nonce used during OAuth flow', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the app is currently installed on this store')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Store',
                'verbose_name_plural': 'Shopify Stores',
                'ordering': ['-installed_at'],
            },
        ),
    ]
