# Generated by Django 6.0 on 2026-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='ai_conversations_limit',
            field=models.IntegerField(default=100, help_text='Maximum AI conversations allowed per billing cycle'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='ai_conversations_used',
            field=models.IntegerField(default=0, help_text='Number of AI conversations used in the current billing cycle'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='plan_name',
            field=models.CharField(default='Free Forever', help_text='Current subscription plan name', max_length=100),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='plan_status',
            field=models.CharField(default='active', help_text='Current subscription status (e.g., active, frozen, cancelled)', max_length=50),
        ),
    ]
