# Generated by Django 6.0 on 2026-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_shopifystore_ai_conversations_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='charge_id',
            field=models.CharField(blank=True, help_text="Shopify recurring charge GID (e.g., 'gid://shopify/AppSubscription/123')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='plan_type',
            field=models.CharField(default='Free', help_text='Type of plan (e.g., Free, Recurring)', max_length=50),
        ),
    ]
