# Generated by Django 6.0 on 2026-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_shopifystore_charge_id_shopifystore_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='consent_customers',
            field=models.BooleanField(default=False, help_text='Whether the merchant has consented to AI reading customers'),
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='consent_orders',
            field=models.BooleanField(default=False, help_text='Whether the merchant has consented to AI reading orders'),
        ),
    ]
